version: "3.9"
services:

  # proxy, used to connect to all the servers via a single bungeecord instance
  proxy:
    container_name: mc-proxy
    image: itzg/bungeecord
    ports:
      - "25565:25565"
    volumes:
      - ./proxy:/server
      - //var/run/docker.sock:/var/run/docker.sock
    environment:
      TYPE: "WATERFALL"
    restart: always
    networks:
      - minecraft

  # hub, welcome server, where players can connect to and choose which server to play on
  mc-hub:
    container_name: mc-hub
    image: itzg/minecraft-server
    stdin_open: true
    user: root
    expose:
      - "25565"
    environment:
      OPS: "SpydeRL"
      SERVER_NAME: "Hub"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      USE_AIKAR_FLAGS: "TRUE"
      TYPE: "${MC_SERVER_TYPE}"
      MAX_MEMORY: "1G"      
      SPIGET_RESOURCES: 19254,27448,34315,1997,49425 # 49425 is the spigot resource id for the DeluxeHub 3 plugin
      MAX_TICK_TIME: "-1"
      ENABLE_AUTOPAUSE: "TRUE"
      MODE: "creative"
    volumes:
      - ./common/ops.json:/data/config/ops.json
      - ./mc-hub:/data
    networks:
      - minecraft

  # creative, for playing creative 
  mc-creative:
    container_name: mc-creative
    image: itzg/minecraft-server
    stdin_open: true
    expose:
      - "25565"
    environment:
      SERVER_NAME: "creative"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      USE_AIKAR_FLAGS: "TRUE"
      TYPE: "${MC_SERVER_TYPE}"
      MAX_MEMORY: "1G"      
      ENFORCE_WHITELIST: "TRUE"
      SPIGET_RESOURCES: 19254,27448,34315,1997
      MAX_TICK_TIME: "-1"
      ENABLE_AUTOPAUSE: "TRUE"
      MODE: "creative"
    volumes:
      - ./common/ops.json:/data/config/ops.json
      - ./mc-creative:/data
    networks:
      - minecraft

  # survival, the survival server, where players can play survival
  mc-survival:
    container_name: mc-survival
    image: itzg/minecraft-server
    stdin_open: true
    expose:
      - "25565"
    environment:
      SERVER_NAME: "Survival"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      USE_AIKAR_FLAGS: "TRUE"
      TYPE: "${MC_SERVER_TYPE}"
      MAX_MEMORY: "1G"      
      ENFORCE_WHITELIST: "TRUE"
      SPIGET_RESOURCES: 19254,27448,34315,1997
      MAX_TICK_TIME: "-1"
      ENABLE_AUTOPAUSE: "TRUE"
      MODE: "survival"
    volumes:
      - ./common/ops.json:/data/config/ops.json
      - ./mc-survival:/data
    networks:
      - minecraft
      
networks:
  minecraft:
    driver: bridge